name: Auto Pull on Update

on:
  push:
    branches:
      - build  # You can change this to any branch you want to monitor

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 🔍 Validate secrets
      run: |
        echo "Validating secrets..."
        if [ -z "${{ secrets.GOINTERLING_FTP_SERVER }}" ]; then
          echo "Error: GOINTERLING_FTP_SERVER is not set."
          exit 1
        fi
        if [ -z "${{ secrets.GOINTERLING_FTP_USERNAME }}" ]; then
          echo "Error: GOINTERLING_FTP_USERNAME is not set."
          exit 1
        fi
        if [ -z "${{ secrets.GOINTERLING_FTP_PASSWORD }}" ]; then
          echo "Error: GOINTERLING_FTP_PASSWORD is not set."
          exit 1
        fi
        echo "All required secrets are set."

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 203.175.9.138
        username: gointerling@gointerling.com
        password: ${{ secrets.GOINTERLING_FTP_PASSWORD }}
        port: 21
        protocol: ftps
