name: Auto Pull on Update

on:
  push:
    branches:
      - build  # You can change this to any branch you want to monitor

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3

    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: gointerling.com
        remote-user: ${{ secrets.DEPLOY_USER }}
        private-ssh-key: ${{ secrets.DEPLOY_KEY }}
        destination-path: ${{ secrets.FE_DEPLOY_PATH }}
