name: Auto Pull on Update

on:
  push:
    branches:
      - build  # You can change this to any branch you want to monitor

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.GOINTERLING_FTP_SERVER }}
        username: ${{ secrets.GOINTERLING_FTP_USERNAME }}
        password: ${{ secrets.GOINTERLING_FTP_PASSWORD }}